on: push
jobs:
  qa:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Clone portal
        uses: actions/checkout@v2
        with:
          repository: ImperialCollegeLondon/hpc_portal
          path: portal
      - name: Install prerequisites
        run: |
          python -m pip install -q -U pip
          python -m pip install -q pyyaml marshmallow
      - name: Validate schema
        run: |
          python portal/config_validation.py portal_config.yaml
